const dataListState = [
  {
    item: "Chicken Biriyani",
    price: 190,
    id: 1,
    restaurant: "Dosa Corner",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Biriyani",
  },
  {
    item: "Dosa",
    price: 100,
    id: 2,
    restaurant: "Dosa Corner",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "South Indian",
  },
  {
    item: "Idli",
    price: 60,
    id: 3,
    restaurant: "Dosa Corner",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "South Indian",
  },
  {
    item: "Chicken Biriyani",
    price: 180,
    id: 4,
    restaurant: "Dosa Corner",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Biriyani",
  },
  {
    item: "Mutton Biriyani",
    price: 280,
    id: 5,
    restaurant: "Dosa Corner",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Biriyani",
  },
  {
    item: "Kung Pav Chicken",
    price: 280,
    i1: 6,
    restaurant: "Dosa Corner",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Chinese",
  },
  {
    item: "Veg Fried Rice",
    price: 150,
    id: 7,
    restaurant: "Dosa Corner",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Chinese",
  },
  {
    item: "Aloo Paratha",
    price: 40,
    id: 8,
    restaurant: "Dosa Corner",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "North Indian",
  },

  {
    item: "dhal makhani",
    price: 150,
    id: 9,
    restaurant: "Kapoor's Cafe",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "North Indian",
  },
  {
    item: "South Indian Meals",
    price: 180,
    id: 10,
    restaurant: "Ramasraya",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "South Indian",
  },
  {
    item: "North Indian Meals",
    price: 210,
    id: 11,
    restaurant: "Kapoor's Cafe",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "North Indian",
  },
  {
    item: "Dosa",
    price: 100,
    id: 12,
    restaurant: "Ramasraya",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "South Indian",
  },
  {
    item: "Dosa",
    price: 130,
    id: 13,
    restaurant: "Udupi Restaurant",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "South Indian",
  },
  {
    item: "Dosa",
    price: 150,
    id: 14,
    restaurant: "A2B",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "South Indian",
  },
  {
    item: "Dosa",
    price: 80,
    id: 14,
    restaurant: "Simhapuri",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "South Indian",
  },
  {
    item: "Chicken Biriyani",
    price: 190,
    id: 15,
    restaurant: "Megnas Biriyani",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Biriyani",
  },
  {
    item: "Idli",
    price: 100,
    id: 16,
    restaurant: "Simhapuri",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "South Indian",
  },
  {
    item: "Idli",
    price: 60,
    id: 17,
    restaurant: "Dosa Corner",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "South Indian",
  },
  {
    item: "Chicken Biriyani",
    price: 180,
    id: 18,
    restaurant: "Manis biriyani",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Biriyani",
  },
  {
    item: "Chicken Biriyani",
    price: 180,
    id: 19,
    restaurant: "Royal Empire",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Biriyani",
  },
  {
    item: "Veg Sandwich",
    price: 100,
    id: 20,
    restaurant: "Royal Empire",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Sandwich",
  },
  {
    item: "Chicken Burger",
    price: 180,
    id: 21,
    restaurant: "Burger King",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Burger",
  },
  {
    item: "Veg Burger",
    price: 150,
    id: 22,
    restaurant: "Burger King",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Burger",
  },
  {
    item: "Paneer Dosa",
    price: 100,
    id: 24,
    restaurant: "Udupi Restaurant",
    description: "The flavourful Rice ",
    image: "../assets/biriyani.jpg",
    category: "Dosa",
  },
  {
    item: "Ragi Dosa",
    price: 140,
    id: 25,
    restaurant: "Udupi Restaurant",
    description: "The flavourful dosa ",
    image: "../assets/biriyani.jpg",
    category: "Dosa",
  },
  {
    item: "Gopi Manjurian",
    price: 150,
    id: 26,
    restaurant: "Udupi Restaurant",
    description: "The flavourful Gopi ",
    image: "../assets/biriyani.jpg",
    category: "Chinese",
  },
  {
    item: "Paneer Manjurian",
    price: 190,
    id: 27,
    restaurant: "A2B",
    description: "The flavourful Rice ",
    image: "../assets/biriyani.jpg",
    category: "North Indian",
  },
  {
    item: "Uthappam",
    price: 70,
    id: 28,
    restaurant: "A2B",
    description: "The flavourful Rice ",
    image: "../assets/biriyani.jpg",
    category: "South indian",
  },
  {
    item: "South Indian Meals",
    price: 170,
    id: 29,
    restaurant: "A2B",
    description: "The flavourful Rice ",
    image: "../assets/biriyani.jpg",
    category: "South indian Meals",
  },
  {
    item: "North Indian Meals",
    price: 170,
    id: 30,
    restaurant: "A2B",
    description: "The flavourful Rice ",
    image: "../assets/biriyani.jpg",
    category: "North Indian Meals",
  },
  {
    item: "North Indian Mealsm",
    price: 70,
    id: 31,
    restaurant: "Ramasraya",
    description: "The flavourful Rice ",
    image: "../assets/biriyani.jpg",
    category: "North indian Meals",
  },
  {
    item: "South indian Meals",
    price: 180,
    id: 32,
    restaurant: "Ramasraya",
    description: "The flavourful Rice ",
    image: "../assets/biriyani.jpg",
    category: "South indian Meals",
  },
  {
    item: "Margeretta Pizza",
    price: 110,
    id: 33,
    restaurant: "Brick Oven",
    description: "The cheesy flavouful pizza ",
    image: "../assets/biriyani.jpg",
    category: "Pizza",
  },
  {
    item: " Corn Cheese Pizza",
    price: 130,
    id: 34,
    restaurant: "Brick Oven",
    description: "The cheesy flavouful pizza ",
    image: "../assets/biriyani.jpg",
    category: "Pizza",
  },
  {
    item: " Chicken Cheese Pizza",
    price: 180,
    id: 35,
    restaurant: "Brick Oven",
    description: "The cheesy flavouful pizza ",
    image: "../assets/biriyani.jpg",
    category: "Pizza",
  },
  {
    item: " Chicken Pepperoni Cheese Pizza",
    price: 220,
    id: 36,
    restaurant: "Brick Oven",
    description: "The cheesy flavouful pizza ",
    image: "../assets/biriyani.jpg",
    category: "Pizza",
  },
  {
    item: "Chicken Biriyani",
    price: 220,
    id: 37,
    restaurant: "Manis biriyani",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Biriyani",
  },
  {
    item: "Mutton Biriyani",
    price: 220,
    id: 38,
    restaurant: "Manis biriyani",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Biriyani",
  },
  {
    item: "Veg Fried Rice",
    price: 180,
    id: 39,
    restaurant: "Manis biriyani",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Chinese",
  },
  {
    item: "Chicken Biriyani",
    price: 220,
    id: 40,
    restaurant: "Star biriyani",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Biriyani",
  },
  {
    item: "Mutton Biriyani",
    price: 220,
    id: 41,
    restaurant: "Star biriyani",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Biriyani",
  },
  {
    item: "Veg Fried Rice",
    price: 180,
    id: 42,
    restaurant: "Star biriyani",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Chinese",
  },
  {
    item: "Chicken Fried Rice",
    price: 180,
    id: 43,
    restaurant: "Megnas Biriyani",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Chinese",
  },
  {
    item: "Mutton Biriyani",
    price: 180,
    id: 44,
    restaurant: "Megnas Biriyani",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Biriyani",
  }, {
    item: "Chicken Kebab",
    price: 180,
    id: 45,
    restaurant: "Empire Restaurant",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Biriyani",
  }, {
    item: "Mutton Biriyani",
    price: 180,
    id: 46,
    restaurant: "Empire Restaurant",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Biriyani",
  }, {
    item: "Chicken Biriyani",
    price: 180,
    id: 47,
    restaurant: "Empire Restaurant",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Biriyani",
  }, {
    item: "Butter Nan",
    price: 180,
    id: 48,
    restaurant: "Empire Restaurant",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Rotis",
  }, {
    item: "Garlic Nan",
    price: 180,
    id: 49,
    restaurant: "Palace Hotel",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Rotis",
  }, {
    item: "Butter Nan",
    price: 180,
    id: 50,
    restaurant: "Royal Empire",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Rotis",
  },{
    item: "Sharjah Shake",
    price: 180,
    id: 51,
    restaurant: "Palace Hotel",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Shakes",
  },{
    item: "Strawberry Shake",
    price: 180,
    id: 52,
    restaurant: "Palace Hotel",
    description: "The yummiest tastiest dosa ",
    image: "../assets/biriyani.jpg",
    category: "Shakes",
  },
  
];

export default dataListState;
